version: '3.8'
services:
  nameserver:
    build:
      context: .                # la raíz del proyecto
      dockerfile: /ServidorNombres/Dockerfile
    container_name: name_server
    ports:
      - "9090:9090"
    networks:
      - backend


networks:
  backend:
    driver: bridge

  # resto del docker-compose
