# sala_view.py
from PyQt6.QtWidgets import QWidget
#from sala_view_ui import Ui_SalaView
#from ronda_view_ui import Ui_RondaView
from PyQt6 import QtCore, QtGui, QtWidgets

class RondaView(QWidget):
    def __init__(self):
        super().__init__()
        self.ui = Ui_RondaView()
        self.ui.setupUi(self)

class Ui_RondaView(object):
    def setupUi(self, RondaView):
        RondaView.setObjectName("RondaView")
        RondaView.resize(1080, 720)
        RondaView.setMinimumSize(QtCore.QSize(1080, 720))
        RondaView.setMaximumSize(QtCore.QSize(1080, 720))
        self.label = QtWidgets.QLabel(parent=RondaView)
        self.label.setGeometry(QtCore.QRect(280, 0, 271, 121))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(50)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.nroronda_label = QtWidgets.QLabel(parent=RondaView)
        self.nroronda_label.setGeometry(QtCore.QRect(560, 0, 271, 121))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(50)
        font.setBold(True)
        self.nroronda_label.setFont(font)
        self.nroronda_label.setObjectName("nroronda_label")
        self.enviar_respuestas_btn = QtWidgets.QPushButton(parent=RondaView)
        self.enviar_respuestas_btn.setGeometry(QtCore.QRect(420, 610, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        self.enviar_respuestas_btn.setFont(font)
        self.enviar_respuestas_btn.setObjectName("enviar_respuestas_btn")
        self.input_categoria1 = QtWidgets.QLineEdit(parent=RondaView)
        self.input_categoria1.setGeometry(QtCore.QRect(400, 140, 481, 41))
        self.input_categoria1.setObjectName("input_categoria1")
        self.categoria1_label = QtWidgets.QLabel(parent=RondaView)
        self.categoria1_label.setGeometry(QtCore.QRect(80, 140, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.categoria1_label.setFont(font)
        self.categoria1_label.setObjectName("categoria1_label")
        self.categoria2_label = QtWidgets.QLabel(parent=RondaView)
        self.categoria2_label.setGeometry(QtCore.QRect(80, 230, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.categoria2_label.setFont(font)
        self.categoria2_label.setObjectName("categoria2_label")
        self.input_categoria2 = QtWidgets.QLineEdit(parent=RondaView)
        self.input_categoria2.setGeometry(QtCore.QRect(400, 230, 481, 41))
        self.input_categoria2.setObjectName("input_categoria2")
        self.categoria3_label = QtWidgets.QLabel(parent=RondaView)
        self.categoria3_label.setGeometry(QtCore.QRect(80, 320, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.categoria3_label.setFont(font)
        self.categoria3_label.setObjectName("categoria3_label")
        self.input_categoria3 = QtWidgets.QLineEdit(parent=RondaView)
        self.input_categoria3.setGeometry(QtCore.QRect(400, 320, 481, 41))
        self.input_categoria3.setObjectName("input_categoria3")
        self.categoria4_label = QtWidgets.QLabel(parent=RondaView)
        self.categoria4_label.setGeometry(QtCore.QRect(80, 410, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.categoria4_label.setFont(font)
        self.categoria4_label.setObjectName("categoria4_label")
        self.input_categoria4 = QtWidgets.QLineEdit(parent=RondaView)
        self.input_categoria4.setGeometry(QtCore.QRect(400, 410, 481, 41))
        self.input_categoria4.setObjectName("input_categoria4")
        self.input_categoria5 = QtWidgets.QLineEdit(parent=RondaView)
        self.input_categoria5.setGeometry(QtCore.QRect(400, 500, 481, 41))
        self.input_categoria5.setObjectName("input_categoria5")
        self.categoria5_label = QtWidgets.QLabel(parent=RondaView)
        self.categoria5_label.setGeometry(QtCore.QRect(80, 500, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.categoria5_label.setFont(font)
        self.categoria5_label.setObjectName("categoria5_label")

        self.retranslateUi(RondaView)
        QtCore.QMetaObject.connectSlotsByName(RondaView)

    def retranslateUi(self, RondaView):
        _translate = QtCore.QCoreApplication.translate
        RondaView.setWindowTitle(_translate("RondaView", "Form"))
        self.label.setText(_translate("RondaView", "Ronda"))
        self.nroronda_label.setText(_translate("RondaView", "<1/3>"))
        self.enviar_respuestas_btn.setText(_translate("RondaView", "STOP!"))
        self.categoria1_label.setText(_translate("RondaView", "<html><head/><body><p align=\"center\">&lt;Categoria1&gt;</p></body></html>"))
        self.categoria2_label.setText(_translate("RondaView", "<html><head/><body><p align=\"center\">&lt;Categoria2&gt;</p></body></html>"))
        self.categoria3_label.setText(_translate("RondaView", "<html><head/><body><p align=\"center\">&lt;Categoria3&gt;</p></body></html>"))
        self.categoria4_label.setText(_translate("RondaView", "<html><head/><body><p align=\"center\">&lt;Categoria4&gt;</p></body></html>"))
        self.categoria5_label.setText(_translate("RondaView", "<html><head/><body><p align=\"center\">&lt;Categoria5&gt;</p></body></html>"))
