# sala_view.py
from PyQt6.QtWidgets import QWidget
#from sala_view_ui import Ui_SalaView
from PyQt6 import QtCore, QtGui, QtWidgets

class SalaView(QWidget):
    def __init__(self):
        super().__init__()
        self.ui = Ui_SalaView()
        self.ui.setupUi(self)


class Ui_SalaView(object):
    def setupUi(self, SalaView):
        SalaView.setObjectName("SalaView")
        SalaView.resize(1080, 720)
        SalaView.setMinimumSize(QtCore.QSize(1080, 720))
        SalaView.setMaximumSize(QtCore.QSize(1080, 720))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        SalaView.setFont(font)
        self.label = QtWidgets.QLabel(parent=SalaView)
        self.label.setGeometry(QtCore.QRect(320, 20, 521, 121))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(50)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.confirmar_jugador_btn = QtWidgets.QPushButton(parent=SalaView)
        self.confirmar_jugador_btn.setGeometry(QtCore.QRect(430, 620, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        self.confirmar_jugador_btn.setFont(font)
        self.confirmar_jugador_btn.setObjectName("confirmar_jugador_btn")
        self.label1 = QtWidgets.QLabel(parent=SalaView)
        self.label1.setGeometry(QtCore.QRect(60, 160, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.nickname_label = QtWidgets.QLabel(parent=SalaView)
        self.nickname_label.setGeometry(QtCore.QRect(190, 160, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        self.nickname_label.setFont(font)
        self.nickname_label.setObjectName("nickname_label")
        self.label1_2 = QtWidgets.QLabel(parent=SalaView)
        self.label1_2.setGeometry(QtCore.QRect(700, 170, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        self.label1_2.setFont(font)
        self.label1_2.setObjectName("label1_2")
        self.nrorondas_label = QtWidgets.QLabel(parent=SalaView)
        self.nrorondas_label.setGeometry(QtCore.QRect(920, 170, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        self.nrorondas_label.setFont(font)
        self.nrorondas_label.setObjectName("nrorondas_label")
        self.label1_3 = QtWidgets.QLabel(parent=SalaView)
        self.label1_3.setGeometry(QtCore.QRect(50, 270, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        self.label1_3.setFont(font)
        self.label1_3.setObjectName("label1_3")
        self.categorias_label = QtWidgets.QLabel(parent=SalaView)
        self.categorias_label.setGeometry(QtCore.QRect(220, 270, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        self.categorias_label.setFont(font)
        self.categorias_label.setObjectName("categorias_label")
        self.label1_5 = QtWidgets.QLabel(parent=SalaView)
        self.label1_5.setGeometry(QtCore.QRect(40, 370, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        self.label1_5.setFont(font)
        self.label1_5.setObjectName("label1_5")
        self.jugadores_label = QtWidgets.QLabel(parent=SalaView)
        self.jugadores_label.setGeometry(QtCore.QRect(300, 370, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        self.jugadores_label.setFont(font)
        self.jugadores_label.setObjectName("jugadores_label")
        self.estado_sala_label = QtWidgets.QLabel(parent=SalaView)
        self.estado_sala_label.setGeometry(QtCore.QRect(720, 510, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        self.estado_sala_label.setFont(font)
        self.estado_sala_label.setObjectName("estado_sala_label")

        self.retranslateUi(SalaView)
        QtCore.QMetaObject.connectSlotsByName(SalaView)

    def retranslateUi(self, SalaView):
        _translate = QtCore.QCoreApplication.translate
        SalaView.setWindowTitle(_translate("SalaView", "Form"))
        self.label.setText(_translate("SalaView", "TUTIFRUTTI"))
        self.confirmar_jugador_btn.setText(_translate("SalaView", "Estoy Listo!"))
        self.label1.setText(_translate("SalaView", "Jugador:"))
        self.nickname_label.setText(_translate("SalaView", "<Pepe>"))
        self.label1_2.setText(_translate("SalaView", "Rondas a Jugar:"))
        self.nrorondas_label.setText(_translate("SalaView", "<3>"))
        self.label1_3.setText(_translate("SalaView", "Categorias: "))
        self.categorias_label.setText(_translate("SalaView", "<Listado_Categorias>"))
        self.label1_5.setText(_translate("SalaView", "Jugadores en Sala: "))
        self.jugadores_label.setText(_translate("SalaView", "<Listado_Categorias>"))
        self.estado_sala_label.setText(_translate("SalaView", "<Msg_Estado_Sala>"))